### ISSUE TITLE
Issue with GooglePlaces SPM Module

### ISSUE THREAD

**Issue by bstillitano** [vfn/GoogleMaps-SP#1]
Hi,

Thank you for porting this over to SPM. Very appreciative. I noticed that while building my project for an M1 simulator, it's throwing this error 

![image](https://user-images.githubusercontent.com/40552246/141462241-579df20f-ef93-4954-b721-718a3a8094bf.png)

**Comment by aebanoidze** [comment]
Same for me, any updates?

**Comment by iSapozhnik** [comment]
Same here. One thing to notice, though, if you put xcframeworks from the release section directly to the app - it does work.

**Comment by nojcc** [comment]
@iSapozhnik Can you explain what you exactly mean by this?

**Comment by mbuchetics** [comment]
Hi all,
it works if you specify the exact version `5.0.0-M1` when adding the package. Also make sure you use the URL `https://github.com/vfn/GoogleMaps-SP`, the readme points to another repository, which is not ready for M1. If you don't specify the exact version, Xcode will pull in version `5.0.0` which is also not M1 ready.

**Comment by bstillitano** [comment]
@mbuchetics can confirm that your suggested approach does in fact work. Closing this issue.
